### ISSUE TITLE
Forgotten Password

### ISSUE THREAD

**Issue by v-elms** [velms/velms#47]
Menthe signs in and then forgets password

**Comment by iBourgeois** [comment]
@v-elms on the login screen, there is a link to request a password reset. if you click that link and enter your email address, you will receive a link that allows you to change your password!

is this not working for you?

**Comment by v-elms** [comment]
I was merely coming up with recurring problems I remembered from before to make sure that it was going to recur.....

**Comment by iBourgeois** [comment]
that's okay. i just want to confirm before I close this issue, lol.
