### ISSUE TITLE
Current tutors are also top admin 

### ISSUE THREAD

**Issue by v-elms** [velms/velms#55]
One board member, deputy director and myself are currently tutors. Will this present a problem? Should we assume different identities aside from our admin and log in to grade mentees?

**Comment by iBourgeois** [comment]
@v-elms Nope, I actually JUST pushed the code to allow for this kind of situation!

The new ACL I was telling you about allows us a TON more freedom than what you had before!

**Comment by v-elms** [comment]
YEAH!!!!!

**Comment by iBourgeois** [comment]
@v-elms If you visit the [create connection](https://velms.ibourgeois.com/admin/connection/create) page, you will see in the dropdown boxes for `tutor` and `mentor` you and myself as options. We are both `admins`. 

It also allows `staff` group members to be assigned as `tutors` or `mentors`
